### ISSUE TITLE
docs building is broken

### ISSUE THREAD

**Issue by mattmezza** [paoloricciuti/sprinkle-js#4]
```
$ npm run build:docs

> sprinkle-js@0.2.14 build:docs
> node automation/docs-from-readme.js

TypeError: Cannot read properties of undefined (reading 'split')
    at getMapFromString (/Users/mattmezza/dev/sprinkle-js/automation/docs-from-readme.js:5:35)
    at /Users/mattmezza/dev/sprinkle-js/automation/docs-from-readme.js:21:26
```

I suspect the regex `const readMeMap = getMapFromString(readMe, /\r\n\#\#\s(.+)\r\n/);` is not working properly. Will try to fix it.

**Comment by mattmezza** [comment]
forgot to mention some details about my platform:
- macOS `12.6` 
- node `v17.5.0`

**Comment by paoloricciuti** [comment]
Yeah i think it might be a problem of line endings...i'll try to look into this
